# Generated by Django 5.1.7 on 2025-07-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="datetime_creatr",
            new_name="datetime_created",
        ),
    ]
