# Generated by Django 5.1.7 on 2025-07-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_datetime_creatr_comment_datetime_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="books.book",
            ),
        ),
    ]
