# Generated by Django 5.1.7 on 2025-07-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_comment_is_active_comment_recommend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="recommend",
            field=models.BooleanField(default=True),
        ),
    ]
